# Generated by Django 6.0.7 on 2026-08-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(choices=[('landslide', '滑坡'), ('collapse', '崩塌'), ('debris_flow', '泥石流'), ('others', '其他')], max_length=20, verbose_name='类型')),
                ('level', models.CharField(choices=[('red', '红色'), ('orange', '橙色'), ('yellow', '黄色'), ('blue', '蓝色')], max_length=10, verbose_name='风险等级')),
                ('status', models.CharField(choices=[('stable', '稳定'), ('attention', '关注'), ('warning', '预警'), ('emergency', '紧急')], default='stable', max_length=20, verbose_name='状态')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='纬度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('village', models.CharField(blank=True, max_length=50, verbose_name='村')),
                ('town', models.CharField(blank=True, max_length=50, verbose_name='镇')),
                ('county', models.CharField(blank=True, max_length=50, verbose_name='县')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='体积(m³)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长度(m)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽度(m)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高度(m)')),
                ('threat_people', models.IntegerField(default=0, verbose_name='威胁人数')),
                ('threat_houses', models.IntegerField(default=0, verbose_name='威胁房屋')),
                ('threat_roads', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='威胁道路长度(m)')),
                ('threat_assets', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='威胁资产(万元)')),
                ('stability_coefficient', models.DecimalField(decimal_places=3, default=1.0, max_digits=5, verbose_name='稳定性系数')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='责任人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系方式')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '隐患点',
                'verbose_name_plural': '隐患点',
                'db_table': 'hazard_point',
                'indexes': [models.Index(fields=['level'], name='hazard_poin_level_b350d0_idx'), models.Index(fields=['status'], name='hazard_poin_status_2049e7_idx'), models.Index(fields=['-created_at'], name='hazard_poin_created_a3cd0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskSlope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('risk_level', models.CharField(choices=[('high', '高风险'), ('medium', '中风险'), ('low', '低风险')], max_length=10, verbose_name='风险等级')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面积(km²)')),
                ('slope_angle', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='坡度(°)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='纬度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hazard_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_slopes', to='hazard.hazardpoint', verbose_name='关联隐患点')),
            ],
            options={
                'verbose_name': '风险斜坡',
                'verbose_name_plural': '风险斜坡',
                'db_table': 'risk_slope',
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('assigned_to', models.CharField(blank=True, max_length=50, verbose_name='执行人')),
                ('assigned_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('result', models.TextField(blank=True, verbose_name='排查结果')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='现场照片')),
                ('hazard_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_tasks', to='hazard.hazardpoint', verbose_name='关联隐患点')),
            ],
            options={
                'verbose_name': '排查任务',
                'verbose_name_plural': '排查任务',
                'db_table': 'inspection_task',
                'indexes': [models.Index(fields=['status'], name='inspection__status_5f3c4e_idx'), models.Index(fields=['-planned_date'], name='inspection__planned_7b054c_idx')],
            },
        ),
    ]
