# Generated by Django 5.1.14 on 2026-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hazard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectiontask",
            name="checkpoint_count",
            field=models.IntegerField(default=1, verbose_name="检查点数"),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="code",
            field=models.CharField(
                blank=True, max_length=30, unique=True, verbose_name="任务编号"
            ),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="duration_minutes",
            field=models.IntegerField(default=0, verbose_name="耗时(分钟)"),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="issue_count",
            field=models.IntegerField(default=0, verbose_name="发现问题数"),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="route_desc",
            field=models.CharField(blank=True, max_length=200, verbose_name="排查路线"),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AddField(
            model_name="inspectiontask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("routine", "日常巡查"),
                    ("special", "专项排查"),
                    ("emergency", "应急排查"),
                    ("periodic", "定期巡检"),
                ],
                default="routine",
                max_length=20,
                verbose_name="任务类型",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectiontask",
            index=models.Index(
                fields=["task_type"], name="inspection__task_ty_00c880_idx"
            ),
        ),
    ]
