# Generated by Django 5.1.14 on 2026-08-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hazard", "0003_region_and_city_district"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="region",
            new_name="hazard_regi_level_f17b98_idx",
            old_name="hazard_regi_level_6c4d0e_idx",
        ),
        migrations.RenameIndex(
            model_name="region",
            new_name="hazard_regi_parent__f1fd96_idx",
            old_name="hazard_regi_parent__b2c1a4_idx",
        ),
    ]
