# Generated by Django 5.1.14 on 2026-08-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hazard", "0002_enhance_inspection_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="EcologyProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="工程编号"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="工程名称")),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("anchor", "锚索加固"),
                            ("drainage", "排水工程"),
                            ("vegetation", "生态恢复"),
                            ("retaining", "挡土墙"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="工程类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("designing", "设计中"),
                            ("approved", "已批复"),
                            ("construction", "施工中"),
                            ("completed", "已完工"),
                            ("archived", "已归档"),
                        ],
                        default="designing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="工程位置"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="设计说明")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="预算(万元)",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度%")),
                (
                    "planned_days",
                    models.IntegerField(default=0, verbose_name="计划工期(天)"),
                ),
                (
                    "done_days",
                    models.IntegerField(default=0, verbose_name="已完成工期(天)"),
                ),
                (
                    "current_milestone",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="当前里程碑"
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        blank=True, default=list, verbose_name="里程碑节点"
                    ),
                ),
                (
                    "designer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="设计单位/人"
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="施工单位"
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="项目负责人"
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "design_date",
                    models.DateField(blank=True, null=True, verbose_name="设计完成日"),
                ),
                (
                    "approve_date",
                    models.DateField(blank=True, null=True, verbose_name="批复日期"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开工日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="计划完工日"),
                ),
                (
                    "actual_end_date",
                    models.DateField(blank=True, null=True, verbose_name="实际完工日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "hazard_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecology_projects",
                        to="hazard.hazardpoint",
                        verbose_name="关联隐患点",
                    ),
                ),
            ],
            options={
                "verbose_name": "治理工程",
                "verbose_name_plural": "治理工程",
                "db_table": "ecology_project",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EffectAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="评估编号"
                    ),
                ),
                ("factor", models.CharField(max_length=100, verbose_name="评估因子")),
                (
                    "before_value",
                    models.CharField(
                        blank=True, default="-", max_length=50, verbose_name="治理前"
                    ),
                ),
                (
                    "after_value",
                    models.CharField(
                        blank=True, default="-", max_length=50, verbose_name="治理后"
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="单位"),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("significant", "显著提升"),
                            ("qualified", "达标"),
                            ("monitoring", "监测中"),
                            ("failed", "未达标"),
                        ],
                        default="monitoring",
                        max_length=20,
                        verbose_name="效果结论",
                    ),
                ),
                ("conclusion", models.TextField(blank=True, verbose_name="评估说明")),
                (
                    "assessor",
                    models.CharField(blank=True, max_length=50, verbose_name="评估人"),
                ),
                (
                    "assess_date",
                    models.DateField(blank=True, null=True, verbose_name="评估日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="ecology.ecologyproject",
                        verbose_name="关联工程",
                    ),
                ),
            ],
            options={
                "verbose_name": "效果评估",
                "verbose_name_plural": "效果评估",
                "db_table": "ecology_assessment",
                "ordering": ["-assess_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.IntegerField(verbose_name="填报进度%")),
                (
                    "done_days",
                    models.IntegerField(default=0, verbose_name="累计完成天数"),
                ),
                (
                    "milestone",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="里程碑说明"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="进度说明")),
                (
                    "reporter",
                    models.CharField(blank=True, max_length=50, verbose_name="填报人"),
                ),
                (
                    "report_date",
                    models.DateField(blank=True, null=True, verbose_name="填报日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="ecology.ecologyproject",
                        verbose_name="关联工程",
                    ),
                ),
            ],
            options={
                "verbose_name": "治理进度",
                "verbose_name_plural": "治理进度",
                "db_table": "ecology_progress_log",
                "ordering": ["-report_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="ecologyproject",
            index=models.Index(fields=["status"], name="ecology_pro_status_711bba_idx"),
        ),
        migrations.AddIndex(
            model_name="ecologyproject",
            index=models.Index(
                fields=["project_type"], name="ecology_pro_project_161ced_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecologyproject",
            index=models.Index(
                fields=["-created_at"], name="ecology_pro_created_5e54ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="effectassessment",
            index=models.Index(fields=["effect"], name="ecology_ass_effect_aa17be_idx"),
        ),
        migrations.AddIndex(
            model_name="effectassessment",
            index=models.Index(
                fields=["project", "-assess_date"],
                name="ecology_ass_project_fecb39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progresslog",
            index=models.Index(
                fields=["project", "-report_date"],
                name="ecology_pro_project_ca4297_idx",
            ),
        ),
    ]
