# Generated by Django 5.1.14 on 2026-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="编号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="装备名称")),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型号"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="存放/使用位置"
                    ),
                ),
                (
                    "last_maint",
                    models.DateField(blank=True, null=True, verbose_name="上次保养"),
                ),
                (
                    "next_maint",
                    models.DateField(blank=True, null=True, verbose_name="下次保养"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("maintain", "待保养"),
                            ("fault", "故障"),
                            ("retired", "报废"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "keeper",
                    models.CharField(blank=True, max_length=50, verbose_name="保管人"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "装备运维",
                "verbose_name_plural": "装备运维",
                "db_table": "equipment_asset",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="MaterialStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="编号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="材料名称")),
                (
                    "spec",
                    models.CharField(blank=True, max_length=100, verbose_name="规格"),
                ),
                (
                    "stock",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="库存"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="件", max_length=20, verbose_name="单位"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="存放位置"
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="最低库存",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "材料库存",
                "verbose_name_plural": "材料库存",
                "db_table": "equipment_material",
                "ordering": ["code"],
            },
        ),
    ]
