# Generated by Django 6.0.7 on 2026-08-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模型编号')),
                ('model_type', models.CharField(choices=[('threshold', '阈值模型'), ('trend', '趋势模型'), ('ml', '机器学习模型'), ('fusion', '融合模型')], max_length=20, verbose_name='模型类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('params', models.JSONField(default=dict, verbose_name='参数配置')),
                ('yellow_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='黄色阈值')),
                ('orange_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='橙色阈值')),
                ('red_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='红色阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预警模型',
                'verbose_name_plural': '预警模型',
                'db_table': 'warning_model',
            },
        ),
        migrations.CreateModel(
            name='WarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='预警编号')),
                ('level', models.CharField(choices=[('red', '红色'), ('orange', '橙色'), ('yellow', '黄色'), ('blue', '蓝色')], max_length=10, verbose_name='预警等级')),
                ('trigger_type', models.CharField(blank=True, max_length=50, verbose_name='触发类型')),
                ('trigger_value', models.JSONField(blank=True, default=dict, verbose_name='触发值')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='置信度')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('analyzing', '研判中'), ('published', '已发布'), ('processing', '处置中'), ('closed', '已闭环')], default='pending', max_length=20, verbose_name='状态')),
                ('call_status', models.CharField(blank=True, max_length=20, verbose_name='叫应状态')),
                ('call_detail', models.JSONField(blank=True, default=dict, verbose_name='叫应详情')),
                ('confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('confirm_user', models.CharField(blank=True, max_length=50, verbose_name='确认人')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('publish_user', models.CharField(blank=True, max_length=50, verbose_name='发布人')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='闭环时间')),
                ('close_reason', models.CharField(blank=True, max_length=200, verbose_name='闭环原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hazard_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='hazard.hazardpoint', verbose_name='隐患点')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'db_table': 'warning_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'level'], name='warning_rec_status_b7d31f_idx'), models.Index(fields=['hazard_point'], name='warning_rec_hazard__a23bdb_idx'), models.Index(fields=['-created_at'], name='warning_rec_created_094212_idx')],
            },
        ),
    ]
