# Generated by Django 5.1.14 on 2026-08-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        default="边坡地质灾害智能预防管控平台",
                        max_length=100,
                        verbose_name="系统名称",
                    ),
                ),
                (
                    "force_threshold",
                    models.CharField(
                        default="85 MPa",
                        max_length=50,
                        verbose_name="预警阈值(牛顿力展示)",
                    ),
                ),
                (
                    "call_timeout_sec",
                    models.IntegerField(default=120, verbose_name="自动呼叫超时(秒)"),
                ),
                (
                    "notify_sms",
                    models.BooleanField(default=True, verbose_name="短信通知"),
                ),
                (
                    "notify_call",
                    models.BooleanField(default=True, verbose_name="电话呼叫"),
                ),
                (
                    "notify_app",
                    models.BooleanField(default=True, verbose_name="APP推送"),
                ),
                (
                    "notify_email",
                    models.BooleanField(default=False, verbose_name="邮件通知"),
                ),
                (
                    "weather_text",
                    models.CharField(
                        default="晴", max_length=50, verbose_name="天气文案"
                    ),
                ),
                (
                    "weather_temp_c",
                    models.IntegerField(default=25, verbose_name="气温℃"),
                ),
                (
                    "weather_icon",
                    models.CharField(
                        default="sunny", max_length=20, verbose_name="天气图标"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展配置"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "syshub_system_config",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("body", models.TextField(blank=True, verbose_name="内容")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "预警"),
                            ("danger", "紧急"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="级别",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="跳转路径"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="system", max_length=50, verbose_name="来源"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="指定用户(空=全员)",
                    ),
                ),
            ],
            options={
                "verbose_name": "站内通知",
                "verbose_name_plural": "站内通知",
                "db_table": "syshub_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "-created_at"],
                        name="syshub_noti_is_read_ee296b_idx",
                    )
                ],
            },
        ),
    ]
