# Generated by Django 6.0.7 on 2026-08-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('device_type', models.CharField(choices=[('npr_anchor', 'NPR锚索计'), ('rainfall', '雨量计'), ('fiber_optic', '光纤光栅'), ('camera', '摄像头'), ('gnss', 'GNSS位移站'), ('inclinometer', '倾角仪'), ('others', '其他')], max_length=20, verbose_name='设备类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('fault', '故障')], default='online', max_length=10, verbose_name='状态')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12, verbose_name='纬度')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='安装位置')),
                ('install_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('range_value', models.CharField(blank=True, max_length=50, verbose_name='量程')),
                ('accuracy', models.CharField(blank=True, max_length=50, verbose_name='精度')),
                ('power_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='功耗(W)')),
                ('battery', models.IntegerField(default=100, verbose_name='电量(%)')),
                ('signal', models.CharField(choices=[('strong', '强'), ('medium', '中'), ('weak', '弱')], default='strong', max_length=10, verbose_name='信号强度')),
                ('last_data_time', models.DateTimeField(blank=True, null=True, verbose_name='最后数据时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hazard_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='hazard.hazardpoint', verbose_name='关联隐患点')),
            ],
            options={
                'verbose_name': '监测设备',
                'verbose_name_plural': '监测设备',
                'db_table': 'monitoring_device',
            },
        ),
        migrations.CreateModel(
            name='MonitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('force', '牛顿力'), ('displacement', '位移'), ('rainfall', '降雨量'), ('stress', '应力'), ('strain', '应变'), ('temperature', '温度')], max_length=20, verbose_name='数据类型')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='数值')),
                ('unit', models.CharField(default='', max_length=10, verbose_name='单位')),
                ('record_time', models.DateTimeField(verbose_name='记录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='monitoring.monitoringdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': '监测数据',
                'verbose_name_plural': '监测数据',
                'db_table': 'monitor_data',
                'ordering': ['-record_time'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringdevice',
            index=models.Index(fields=['device_type'], name='monitoring__device__e4057d_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringdevice',
            index=models.Index(fields=['status'], name='monitoring__status_55d799_idx'),
        ),
        migrations.AddIndex(
            model_name='monitordata',
            index=models.Index(fields=['device', '-record_time'], name='monitor_dat_device__7d4e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='monitordata',
            index=models.Index(fields=['data_type', '-record_time'], name='monitor_dat_data_ty_2ab2f9_idx'),
        ),
    ]
