# Generated by Django 5.1.14 on 2026-08-13 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MqttIngestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=200, verbose_name="主题"),
                ),
                (
                    "device_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        verbose_name="设备编号",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="报文"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "已受理"),
                            ("processed", "已处理"),
                            ("failed", "失败"),
                        ],
                        default="accepted",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="错误"),
                ),
                (
                    "monitor_data_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="监测数据ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "MQTT接入日志",
                "verbose_name_plural": "MQTT接入日志",
                "db_table": "mqtt_ingest_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="mqtt_ingest_created_1acf1f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MonitorDailyAgg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("force", "牛顿力"),
                            ("displacement", "位移"),
                            ("rainfall", "降雨量"),
                            ("stress", "应力"),
                            ("strain", "应变"),
                            ("temperature", "温度"),
                        ],
                        max_length=20,
                        verbose_name="数据类型",
                    ),
                ),
                ("day", models.DateField(verbose_name="日期")),
                ("count", models.IntegerField(default=0, verbose_name="样本数")),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="最小",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="最大",
                    ),
                ),
                (
                    "avg_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=15,
                        null=True,
                        verbose_name="平均",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_aggs",
                        to="monitoring.monitoringdevice",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "监测日聚合",
                "verbose_name_plural": "监测日聚合",
                "db_table": "monitor_daily_agg",
                "indexes": [
                    models.Index(
                        fields=["day", "data_type"], name="monitor_dai_day_d4fe3d_idx"
                    ),
                    models.Index(
                        fields=["device", "-day"], name="monitor_dai_device__e95f5f_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device", "data_type", "day"),
                        name="uniq_monitor_daily_agg",
                    )
                ],
            },
        ),
    ]
