# Generated by Django 5.1.14 on 2026-08-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_iot_daily_agg_and_ingest_log"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monitordailyagg",
            name="uniq_monitor_daily_agg",
        ),
        migrations.AddField(
            model_name="monitordailyagg",
            name="channel",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="通道"
            ),
        ),
        migrations.AddField(
            model_name="monitordata",
            name="channel",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=16,
                verbose_name="通道",
            ),
        ),
        migrations.AddIndex(
            model_name="monitordata",
            index=models.Index(
                fields=["device", "data_type", "channel", "-record_time"],
                name="monitor_dat_device__916e5c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="monitordailyagg",
            constraint=models.UniqueConstraint(
                fields=("device", "data_type", "channel", "day"),
                name="uniq_monitor_daily_agg",
            ),
        ),
    ]
