# Generated by Django 5.1.14 on 2026-08-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_monitor_data_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="mqttingestlog",
            name="trace_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="TraceId"
            ),
        ),
        migrations.AddIndex(
            model_name="mqttingestlog",
            index=models.Index(
                fields=["trace_id", "-created_at"],
                name="mqtt_ingest_trace_i_23c47a_idx",
            ),
        ),
    ]
