# Generated by Django 5.1.14 on 2026-08-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hazard", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="剖面编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="剖面名称")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="位置"),
                ),
                (
                    "direction",
                    models.CharField(blank=True, max_length=50, verbose_name="走向"),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=10,
                        verbose_name="长度(m)",
                    ),
                ),
                (
                    "profile_points",
                    models.JSONField(blank=True, default=list, verbose_name="剖面点"),
                ),
                (
                    "layers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{key, label, color}]",
                        verbose_name="地层说明",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hazard_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_sections",
                        to="hazard.hazardpoint",
                        verbose_name="关联隐患点",
                    ),
                ),
            ],
            options={
                "verbose_name": "地质剖面",
                "verbose_name_plural": "地质剖面",
                "db_table": "geology_cross_section",
                "ordering": ["code"],
            },
        ),
    ]
