# Generated by Django 5.1.14 on 2026-08-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geology", "0001_initial"),
        ("hazard", "0004_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeologySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="场景编号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="场景名称")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(default=2500, verbose_name="相机高度(m)"),
                ),
                (
                    "tileset_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="3D Tiles URL"
                    ),
                ),
                (
                    "ion_asset_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Cesium Ion Asset Id"
                    ),
                ),
                (
                    "glb_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="GLB/GLTF URL"
                    ),
                ),
                (
                    "cover_url",
                    models.CharField(blank=True, max_length=500, verbose_name="封面图"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "归档"),
                        ],
                        default="published",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hazard_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geology_sites",
                        to="hazard.hazardpoint",
                        verbose_name="关联隐患点",
                    ),
                ),
            ],
            options={
                "verbose_name": "三维站点场景",
                "verbose_name_plural": "三维站点场景",
                "db_table": "geology_site",
                "ordering": ["-updated_at"],
            },
        ),
    ]
