# Generated by Django 6.0.7 on 2026-08-03 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hazard', '0001_initial'),
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='预案名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='预案编号')),
                ('level', models.CharField(choices=[('1', '一级'), ('2', '二级'), ('3', '三级'), ('4', '四级')], max_length=5, verbose_name='响应等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效'), ('archived', '已归档')], default='draft', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='预案描述')),
                ('content', models.JSONField(default=dict, verbose_name='预案内容')),
                ('applicable_scenarios', models.JSONField(blank=True, default=list, verbose_name='适用场景')),
                ('commander', models.CharField(blank=True, max_length=50, verbose_name='指挥人')),
                ('commander_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应急预案',
                'verbose_name_plural': '应急预案',
                'db_table': 'emergency_plan',
            },
        ),
        migrations.CreateModel(
            name='EmergencySupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物资名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物资编号')),
                ('category', models.CharField(choices=[('food', '食品'), ('water', '饮用水'), ('tent', '帐篷'), ('medical', '医疗用品'), ('tool', '工具设备'), ('other', '其他')], max_length=20, verbose_name='类别')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='单位')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('responsible_person', models.CharField(blank=True, max_length=50, verbose_name='负责人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('last_check_date', models.DateField(blank=True, null=True, verbose_name='最后检查日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应急物资',
                'verbose_name_plural': '应急物资',
                'db_table': 'emergency_supply',
            },
        ),
        migrations.CreateModel(
            name='EvacuationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('status', models.CharField(choices=[('pending', '待转移'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('total_people', models.IntegerField(default=0, verbose_name='需转移人数')),
                ('transferred_people', models.IntegerField(default=0, verbose_name='已转移人数')),
                ('shelter_name', models.CharField(blank=True, max_length=100, verbose_name='安置点名称')),
                ('shelter_address', models.CharField(blank=True, max_length=200, verbose_name='安置点地址')),
                ('route_path', models.JSONField(blank=True, default=list, verbose_name='路线坐标')),
                ('route_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='路线距离(km)')),
                ('estimated_time', models.IntegerField(default=0, verbose_name='预计时间(分钟)')),
                ('commander', models.CharField(blank=True, max_length=50, verbose_name='指挥人')),
                ('commander_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('grid_worker', models.CharField(blank=True, max_length=50, verbose_name='网格员')),
                ('grid_phone', models.CharField(blank=True, max_length=20, verbose_name='网格员电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hazard_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_tasks', to='hazard.hazardpoint', verbose_name='关联隐患点')),
                ('warning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_tasks', to='warning.warningrecord', verbose_name='关联预警')),
            ],
            options={
                'verbose_name': '避险转移任务',
                'verbose_name_plural': '避险转移任务',
                'db_table': 'evacuation_task',
                'indexes': [models.Index(fields=['status'], name='evacuation__status_8bb9c5_idx'), models.Index(fields=['-created_at'], name='evacuation__created_93cdaa_idx')],
            },
        ),
    ]
