# Generated by Django 5.1.14 on 2026-08-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evacuationtask",
            name="shelter_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="安置点纬度",
            ),
        ),
        migrations.AddField(
            model_name="evacuationtask",
            name="shelter_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=12,
                null=True,
                verbose_name="安置点经度",
            ),
        ),
    ]
