# Generated by Django 5.1.14 on 2026-08-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="请求ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, verbose_name="用户名"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, verbose_name="IP"
                    ),
                ),
                (
                    "method",
                    models.CharField(db_index=True, max_length=10, verbose_name="方法"),
                ),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="路径"
                    ),
                ),
                (
                    "query",
                    models.CharField(blank=True, max_length=300, verbose_name="查询串"),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="状态码"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时ms"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=300, verbose_name="UA"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "API审计日志",
                "verbose_name_plural": "API审计日志",
                "db_table": "api_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "path"],
                        name="api_audit_l_created_98af57_idx",
                    ),
                    models.Index(
                        fields=["username", "-created_at"],
                        name="api_audit_l_usernam_301524_idx",
                    ),
                ],
            },
        ),
    ]
